# Change these first
owner: muuvlabs-upptime # Your GitHub organization or username, where this repository lives
repo: muuvlabs-upptime # The name of this repository

sites:
  - name: Community Production
    url: https://community.sebrands.com/community/_healthz
  - name: Program Engine Production
    url: https://pe.sebrands.com/pe/_healthz
  - name: Nutrition Production
    url: https://nutrition.sebrands.com/nutrition/_healthz
  - name: Referrals Production
    url: https://referrals.sebrands.com/referrals/scripts/landing.js
  - name: VHS Production
    url: https://vhs.sebrands.com/vhs/episodes
  - name: Community Staging
    url: https://stage-community.sebrands.com/community/_healthz
  - name: Program Engine Staging
    url: https://stage-pe.sebrands.com/pe/_healthz
  - name: Nutrition Staging
    url: https://stage-nutrition.sebrands.com/nutrition/_healthz
  - name: Referrals Staging
    url: https://stage-referrals.sebrands.com/referrals/scripts/landing.js
  - name: VHS Staging
    url: https://stage-vhs.sebrands.com/vhs/episodes
  - name: Fake website 2
    url: https://veryrealwebsite.fr
  - name: Fake website 3
    url: https://veryrealwebsite.fosho
  - name: Fake website
    url: https://veryrealwebsite.again

status-website:
  baseUrl: /muuvlabs-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Services Upp status"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
