# Change these first
owner: muuvlabs-upptime # Your GitHub organization or username, where this repository lives
repo: muuvlabs-upptime # The name of this repository

sites:
  - name: Community Production
    url: https://community.sebrands.com/community/_healthz
  - name: Program Engine Production
    url: https://pe.sebrands.com/pe/_healthz
  - name: Nutrition Production
    url: https://nutrition.sebrands.com/nutrition/_healthz
  - name: Referrals Production
    url: https://referrals.sebrands.com/referrals/scripts/landing.js
  - name: VHS Production
    url: https://vhs.sebrands.com/vhs/episodes
  - name: muuvlabs.com Website
    url: https://muuvlabs.com/
  - name: api.muuvlabs.com
    url: https://api.muuvlabs.com/
  - name: muuv.fit website
    url: https://muuv.fit/
  - name: muuv.fit API
    url: https://muuv.fit/api/users/me
  - name: 24go API
    url: https://api.24go.co/users/me

status-website:
  baseUrl: /muuvlabs-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Services Upp status"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
